version: "3"
services:
  curl:
    build:
      context: centos/6/curl
    image: centos:6-curl
  scm:
    build:
      context: centos/6/scm
    image: centos:6-scm
  rpmbuild:
    build:
      context: centos/6/rpmbuild
    image: centos:6-rpmbuild
  curlbuild:
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm6:/home/centos/rpmbuild/RPMS
    build:
      context: .
    image: centos:6-curlbuild

volumes:
  rpms:
  rpm6:
  rpm7:
