version: "3.4"
services:
  webrepo:
    volumes:
      - rpm6:/home/centos-6/rpmbuild/RPMS
      - rpm7:/home/centos-7/rpmbuild/RPMS
    build:
      context: rpmbuild/webrepo
    image: rpmbuild:webrepo
  createrepo7:
    volumes:
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: rpmbuild/createrepo
    image: rpmbuild:createrepo
    restart: always
  curlbuild7:
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: .
    image: rpmbuild:7-curlbuild

volumes:
  rpms:
    name: rpms
  rpm6:
    name: rpm6
  rpm7:
    name: rpm7
